language: go

go:
  - 1.8.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/cover

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - golint ./...
  - go vet ./...
  - go test -v ./...

after_success:
  # - go test -coverprofile=profile.out -covermode=set
  # - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always